//! Auditable report for the P7 executable backend scheduling matrix.

use super::*;
use sha2::{Digest, Sha256};
use std::io::Read;

const BACKENDS: [&str; 6] = ["cpp", "c", "interp", "cranelift", "wasm", "assemblyscript"];
const MODES: [&str; 3] = ["scalar", "vec0", "vec1"];
const STRATEGIES: [u8; 4] = [0, 1, 2, 3];
const EXPECTED_SUPPORTED_DSP_COUNT: usize = 92;
const EXCLUDED_DSP_STEMS: [&str; 1] = ["subcontainer1"];
const DEFAULT_ARTIFACT_ROOT: &str = "tests/impulse-tests/ir";
const DEFAULT_REPORT_PATH: &str = "porting/generated/p7-executable-backend-matrix-2026-07-14-en.md";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct MatrixCombination {
    backend: &'static str,
    mode: &'static str,
    strategy: u8,
}

impl MatrixCombination {
    fn directory_name(self) -> String {
        if self.mode == "scalar" {
            format!("{}-ss{}", self.backend, self.strategy)
        } else {
            format!("{}-{}-ss{}", self.backend, self.mode, self.strategy)
        }
    }
}

#[derive(Debug, Eq, PartialEq)]
struct CombinationSummary {
    dsp_count: usize,
    bytes: u64,
    sha256: String,
}

#[derive(Debug)]
struct ReportOptions {
    artifact_root: PathBuf,
    output: PathBuf,
}

/// Verifies every generated P7 matrix response and writes a deterministic
/// repository-relative report. This runs only after `p7-matrix` has compared
/// every response against the C++ oracle successfully.
pub(crate) fn p7_matrix_report(
    args: impl Iterator<Item = String>,
) -> Result<(), Box<dyn std::error::Error>> {
    let options = parse_options(args)?;
    let root = workspace_root();
    let corpus_root = root.join("tests/impulse-tests/dsp");
    let cases = supported_dsp_stems(&corpus_root)?;
    if cases.len() != EXPECTED_SUPPORTED_DSP_COUNT {
        return Err(format!(
            "P7 corpus changed: expected {EXPECTED_SUPPORTED_DSP_COUNT} supported DSPs, found {}",
            cases.len()
        )
        .into());
    }

    let artifact_root = resolve_from_root(&root, &options.artifact_root);
    let output = resolve_from_root(&root, &options.output);
    let combinations = matrix_combinations();
    let mut rows = Vec::with_capacity(combinations.len());
    let mut total_bytes = 0u64;
    for combination in combinations {
        let summary = summarize_combination(&artifact_root, combination, &cases)?;
        total_bytes = total_bytes
            .checked_add(summary.bytes)
            .ok_or("P7 matrix byte count overflow")?;
        rows.push((combination, summary));
    }

    let mut report = String::new();
    writeln!(report, "# P7 Executable Backend Scheduling Matrix")?;
    writeln!(report)?;
    writeln!(
        report,
        "Generated by `cargo run -p xtask -- p7-matrix-report` after a fresh `p7-clean` followed by a complete `p7-matrix` run."
    )?;
    writeln!(report)?;
    writeln!(report, "- Date: 2026-07-14")?;
    writeln!(report, "- Result: **PASS**")?;
    writeln!(report, "- Executable backends: {}", BACKENDS.len())?;
    writeln!(report, "- Modes per backend: {}", MODES.len())?;
    writeln!(report, "- Scheduling strategies: {}", STRATEGIES.len())?;
    writeln!(report, "- Supported DSPs: {}", cases.len())?;
    writeln!(
        report,
        "- Differential comparisons: {}",
        rows.len() * cases.len()
    )?;
    writeln!(report, "- Generated response bytes: {total_bytes}")?;
    writeln!(
        report,
        "- Excluded known compile gap: `{}`",
        EXCLUDED_DSP_STEMS[0]
    )?;
    writeln!(report)?;
    writeln!(
        report,
        "Each row hash binds the sorted DSP names and exact generated response bytes for one backend/mode/strategy combination. A report is emitted only when all expected non-empty response files exist; the preceding Make gate deletes a response whenever `filesCompare` rejects it."
    )?;
    writeln!(report)?;
    writeln!(
        report,
        "| Backend | Mode | `-ss` | DSPs | Bytes | SHA-256 |"
    )?;
    writeln!(report, "|---|---:|---:|---:|---:|---|")?;
    for (combination, summary) in rows {
        writeln!(
            report,
            "| {} | {} | {} | {} | {} | `{}` |",
            combination.backend,
            combination.mode,
            combination.strategy,
            summary.dsp_count,
            summary.bytes,
            summary.sha256
        )?;
    }
    writeln!(report)?;
    writeln!(
        report,
        "This report is translation-validation evidence for the executable impulse prefix/full-pass contracts. It is not a proof of `V-Simulation` and does not close the remaining P7 artifact, precision, final-state/effect, coverage, optimization, or cost-model gates."
    )?;

    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&output, report)?;
    println!("updated {}", workspace_relative_path(&output));
    Ok(())
}

fn parse_options(
    mut args: impl Iterator<Item = String>,
) -> Result<ReportOptions, Box<dyn std::error::Error>> {
    let mut artifact_root = PathBuf::from(DEFAULT_ARTIFACT_ROOT);
    let mut output = PathBuf::from(DEFAULT_REPORT_PATH);
    while let Some(arg) = args.next() {
        match arg.as_str() {
            "--artifact-root" => {
                artifact_root =
                    PathBuf::from(args.next().ok_or("missing value after --artifact-root")?);
            }
            "--out" => {
                output = PathBuf::from(args.next().ok_or("missing value after --out")?);
            }
            other => return Err(format!("unknown p7-matrix-report option: {other}").into()),
        }
    }
    Ok(ReportOptions {
        artifact_root,
        output,
    })
}

fn resolve_from_root(root: &Path, path: &Path) -> PathBuf {
    if path.is_absolute() {
        path.to_path_buf()
    } else {
        root.join(path)
    }
}

fn matrix_combinations() -> Vec<MatrixCombination> {
    let mut combinations = Vec::with_capacity(BACKENDS.len() * MODES.len() * STRATEGIES.len());
    for backend in BACKENDS {
        for mode in MODES {
            for strategy in STRATEGIES {
                combinations.push(MatrixCombination {
                    backend,
                    mode,
                    strategy,
                });
            }
        }
    }
    combinations
}

fn supported_dsp_stems(corpus_root: &Path) -> Result<Vec<String>, Box<dyn std::error::Error>> {
    let mut stems = BTreeSet::new();
    for entry in fs::read_dir(corpus_root)? {
        let path = entry?.path();
        if path.extension().and_then(|ext| ext.to_str()) != Some("dsp") {
            continue;
        }
        let stem = path
            .file_stem()
            .and_then(|name| name.to_str())
            .ok_or_else(|| format!("non-UTF-8 DSP path: {}", path.display()))?;
        if !EXCLUDED_DSP_STEMS.contains(&stem) {
            stems.insert(stem.to_owned());
        }
    }
    Ok(stems.into_iter().collect())
}

fn summarize_combination(
    artifact_root: &Path,
    combination: MatrixCombination,
    cases: &[String],
) -> Result<CombinationSummary, Box<dyn std::error::Error>> {
    let directory = artifact_root.join(combination.directory_name());
    let mut hasher = Sha256::new();
    hasher.update(b"faust-rs-p7-matrix-v1\0");
    let mut bytes = 0u64;
    let mut buffer = vec![0u8; 1024 * 1024];
    for case in cases {
        let path = directory.join(format!("{case}.ir"));
        let mut file = fs::File::open(&path)
            .map_err(|err| format!("missing P7 response {}: {err}", path.display()))?;
        let size = file.metadata()?.len();
        if size == 0 {
            return Err(format!("empty P7 response: {}", path.display()).into());
        }
        hasher.update(case.as_bytes());
        hasher.update([0]);
        loop {
            let read = file.read(&mut buffer)?;
            if read == 0 {
                break;
            }
            hasher.update(&buffer[..read]);
        }
        hasher.update([0]);
        bytes = bytes
            .checked_add(size)
            .ok_or("P7 combination byte count overflow")?;
    }
    Ok(CombinationSummary {
        dsp_count: cases.len(),
        bytes,
        sha256: format!("{:x}", hasher.finalize()),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn matrix_has_all_six_backends_three_modes_and_four_strategies() {
        let combinations = matrix_combinations();
        assert_eq!(combinations.len(), 72);
        assert_eq!(combinations[0].directory_name(), "cpp-ss0");
        assert_eq!(
            combinations
                .last()
                .expect("last combination")
                .directory_name(),
            "assemblyscript-vec1-ss3"
        );
    }

    #[test]
    fn combination_hash_binds_case_names_and_response_bytes() {
        let root =
            std::env::temp_dir().join(format!("faust-rs-p7-matrix-report-{}", std::process::id()));
        let combination = MatrixCombination {
            backend: "cpp",
            mode: "scalar",
            strategy: 0,
        };
        let directory = root.join(combination.directory_name());
        fs::create_dir_all(&directory).expect("create fixture directory");
        fs::write(directory.join("a.ir"), b"a response").expect("write a");
        fs::write(directory.join("b.ir"), b"b response").expect("write b");
        let cases = vec!["a".to_owned(), "b".to_owned()];

        let first = summarize_combination(&root, combination, &cases).expect("summarize fixture");
        assert_eq!(first.dsp_count, 2);
        assert_eq!(first.bytes, 20);
        fs::write(directory.join("b.ir"), b"changed response").expect("change b");
        let second = summarize_combination(&root, combination, &cases).expect("resummarize");
        assert_ne!(first.sha256, second.sha256);

        fs::remove_dir_all(root).expect("remove fixture directory");
    }
}
