//! Generated parity and migration report workflows.
//!
//! The commands in this module read Rust and C++ source artifacts and emit
//! repository documentation under `porting/`. They are diagnostic tools for
//! tracking porting coverage, not part of the compiler runtime path.

use super::*;

// ---------------------------------------------------------------------------
// Differential report generation
// ---------------------------------------------------------------------------

/// Regenerates the parser/lexer parity coverage report under `porting/`.
pub(crate) fn parser_parity_report() -> Result<(), Box<dyn std::error::Error>> {
    let root = workspace_root();
    let cpp_root = PathBuf::from(CPP_SOURCE_ROOT);

    let cpp_parser = cpp_root.join("compiler/parser/faustparser.y");
    let cpp_lexer = cpp_root.join("compiler/parser/faustlexer.l");
    let rust_parser = root.join("crates/parser/src/grammar/faustparser.y");
    let rust_lexer = root.join("crates/parser/src/grammar/faustlexer.l");
    let report_path = root.join(PARITY_REPORT_REL_PATH);

    for path in [&cpp_parser, &cpp_lexer, &rust_parser, &rust_lexer] {
        if !path.exists() {
            return Err(format!("missing input file for parity report: {}", path.display()).into());
        }
    }

    let cpp_parser_src = fs::read_to_string(&cpp_parser)?;
    let cpp_lexer_src = fs::read_to_string(&cpp_lexer)?;
    let rust_parser_src = fs::read_to_string(&rust_parser)?;
    let rust_lexer_src = fs::read_to_string(&rust_lexer)?;

    let cpp_parser_tokens = extract_parser_tokens(&cpp_parser_src);
    let rust_parser_tokens = extract_parser_tokens(&rust_parser_src);
    let cpp_lexer_tokens = extract_cpp_lexer_emitted_tokens(&cpp_lexer_src);
    let rust_lexer_tokens = extract_rust_lexer_emitted_tokens(&rust_lexer_src);
    let cpp_lexer_states = extract_lexer_states(&cpp_lexer_src);
    let rust_lexer_states = extract_lexer_states(&rust_lexer_src);
    let cpp_nonterms = extract_cpp_nonterminals(&cpp_parser_src);
    let rust_nonterms = extract_rust_nonterminals(&rust_parser_src);

    let parser_token_extra = diff_sorted(&rust_parser_tokens, &cpp_parser_tokens);
    let parser_token_missing_exact = diff_sorted(&cpp_parser_tokens, &rust_parser_tokens);
    let (parser_token_alias_covered, parser_token_missing_unresolved) = partition_with_aliases(
        &parser_token_missing_exact,
        &rust_parser_tokens,
        token_aliases,
    );

    let lexer_state_extra = diff_sorted(&rust_lexer_states, &cpp_lexer_states);
    let lexer_state_missing = diff_sorted(&cpp_lexer_states, &rust_lexer_states);

    let nonterm_extra = diff_sorted(&rust_nonterms, &cpp_nonterms);
    let nonterm_missing_exact = diff_sorted(&cpp_nonterms, &rust_nonterms);
    let (nonterm_alias_covered, nonterm_missing_unresolved) =
        partition_with_aliases(&nonterm_missing_exact, &rust_nonterms, nonterminal_aliases);

    let cpp_declared_not_lexed = diff_sorted(&cpp_parser_tokens, &cpp_lexer_tokens);
    let rust_declared_not_lexed = diff_sorted(&rust_parser_tokens, &rust_lexer_tokens);
    let cpp_lexed_not_declared = diff_sorted(&cpp_lexer_tokens, &cpp_parser_tokens);
    let rust_lexed_not_declared = diff_sorted(&rust_lexer_tokens, &rust_parser_tokens);

    let mut out = String::new();
    writeln!(
        &mut out,
        "# Phase 3 Parser/Lexer Parity Coverage Report (Auto-generated)"
    )?;
    writeln!(&mut out)?;
    writeln!(
        &mut out,
        "Generated by: `cargo run -p xtask -- parser-parity-report`"
    )?;
    writeln!(&mut out)?;
    writeln!(&mut out, "## Inputs")?;
    writeln!(&mut out, "- C++ parser: `{}`", cpp_parser.display())?;
    writeln!(&mut out, "- C++ lexer: `{}`", cpp_lexer.display())?;
    writeln!(&mut out, "- Rust parser: `{}`", rust_parser.display())?;
    writeln!(&mut out, "- Rust lexer: `{}`", rust_lexer.display())?;
    writeln!(&mut out)?;
    writeln!(&mut out, "## Summary")?;
    writeln!(
        &mut out,
        "- Parser token coverage: C++ declared `{}` / Rust declared `{}` / unresolved missing `{}`",
        cpp_parser_tokens.len(),
        rust_parser_tokens.len(),
        parser_token_missing_unresolved.len()
    )?;
    writeln!(
        &mut out,
        "- Lexer state coverage: C++ `{}` / Rust `{}` / unresolved missing `{}`",
        cpp_lexer_states.len(),
        rust_lexer_states.len(),
        lexer_state_missing.len()
    )?;
    writeln!(
        &mut out,
        "- Grammar nonterminal coverage (name-based): C++ `{}` / Rust `{}` / unresolved missing `{}`",
        cpp_nonterms.len(),
        rust_nonterms.len(),
        nonterm_missing_unresolved.len()
    )?;
    writeln!(&mut out)?;
    writeln!(&mut out, "## Parser Tokens (C++ `%token` vs Rust `%token`)")?;
    writeln!(
        &mut out,
        "_Note: `exact name` mismatches below are not necessarily missing functionality; they can be covered by explicit alias mapping._"
    )?;
    render_list(
        &mut out,
        "Exact-name mismatch candidates (C++ name not present as-is in Rust)",
        &parser_token_missing_exact,
    )?;
    render_alias_list(
        &mut out,
        "Exact-name mismatches covered by explicit alias mapping (no action required)",
        &parser_token_alias_covered,
    )?;
    render_list(
        &mut out,
        "Unresolved missing after alias mapping (action required)",
        &parser_token_missing_unresolved,
    )?;
    render_list(&mut out, "Extra in Rust", &parser_token_extra)?;

    writeln!(&mut out)?;
    writeln!(&mut out, "## Lexer States (`%x`/`%s`)")?;
    render_list(
        &mut out,
        "Missing in Rust lexer state declarations",
        &lexer_state_missing,
    )?;
    render_list(
        &mut out,
        "Extra in Rust lexer state declarations",
        &lexer_state_extra,
    )?;

    writeln!(&mut out)?;
    writeln!(&mut out, "## Grammar Nonterminals (name-based)")?;
    writeln!(
        &mut out,
        "_Note: `exact name` mismatches below are not necessarily missing functionality; they can be covered by explicit alias mapping (for example dedicated C++ rules grouped under `Primitive` in Rust)._"
    )?;
    render_list(
        &mut out,
        "Exact-name mismatch candidates (C++ nonterminal not present as-is in Rust)",
        &nonterm_missing_exact,
    )?;
    render_alias_list(
        &mut out,
        "Exact-name mismatches covered by explicit alias mapping (no action required)",
        &nonterm_alias_covered,
    )?;
    render_list(
        &mut out,
        "Unresolved missing after alias mapping (action required)",
        &nonterm_missing_unresolved,
    )?;
    render_list(&mut out, "Extra in Rust", &nonterm_extra)?;

    writeln!(&mut out)?;
    writeln!(
        &mut out,
        "## Parser/Lexer Internal Consistency (declared tokens vs lexer emissions)"
    )?;
    render_list(
        &mut out,
        "C++ parser-declared tokens not emitted by C++ lexer",
        &cpp_declared_not_lexed,
    )?;
    render_list(
        &mut out,
        "Rust parser-declared tokens not emitted by Rust lexer",
        &rust_declared_not_lexed,
    )?;
    render_list(
        &mut out,
        "C++ lexer-emitted tokens not declared in C++ parser",
        &cpp_lexed_not_declared,
    )?;
    render_list(
        &mut out,
        "Rust lexer-emitted tokens not declared in Rust parser",
        &rust_lexed_not_declared,
    )?;

    let unresolved_total = parser_token_missing_unresolved.len()
        + lexer_state_missing.len()
        + nonterm_missing_unresolved.len();
    let consistency_issues_total = cpp_declared_not_lexed.len()
        + rust_declared_not_lexed.len()
        + cpp_lexed_not_declared.len()
        + rust_lexed_not_declared.len();

    writeln!(&mut out)?;
    writeln!(&mut out, "## Next Actions")?;
    if unresolved_total == 0 {
        writeln!(
            &mut out,
            "- Unresolved missing items after alias mapping are `0` for parser tokens, lexer states, and grammar nonterminals."
        )?;
    } else {
        writeln!(
            &mut out,
            "- Resolve all items listed in `Unresolved missing after alias mapping (action required)` for tokens and nonterminals."
        )?;
    }
    if consistency_issues_total > 0 {
        writeln!(
            &mut out,
            "- Triage items listed under `Parser/Lexer Internal Consistency` (C++ or Rust declared/emitted token mismatches)."
        )?;
    }
    writeln!(
        &mut out,
        "- Keep this report regenerated at each parser/lexer migration increment to track closure toward 100% parity."
    )?;

    if let Some(parent) = report_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&report_path, out)?;
    println!("updated {}", report_path.display());
    Ok(())
}

#[derive(Clone, Debug)]
/// Normalized success/failure summary for one compiler/reference case run.
pub(crate) struct CaseStatus {
    ok: bool,
    stage: &'static str,
    reason: String,
}

/// Regenerates the C++ vs Rust corpus status report for the parser/signal path.
pub(crate) fn corpus_status_report() -> Result<(), Box<dyn std::error::Error>> {
    let root = workspace_root();
    let report_path = root.join(CORPUS_STATUS_REPORT_REL_PATH);
    let files = corpus_files()?;
    let compiler = compiler::Compiler::new();
    let (cpp_bin, cpp_bin_is_fallback) = resolve_cpp_faust_bin();

    let mut total = 0usize;
    let mut ok_ok = 0usize;
    let mut err_err = 0usize;
    let mut ok_err = 0usize;
    let mut err_ok = 0usize;

    let mut rows = Vec::with_capacity(files.len());
    for file in files {
        let case = case_name(&file)?;
        let cpp = cpp_case_status(&cpp_bin, &file)?;
        let rust = rust_case_status(&compiler, &file);
        total = total.saturating_add(1);

        match (cpp.ok, rust.ok) {
            (true, true) => ok_ok = ok_ok.saturating_add(1),
            (false, false) => err_err = err_err.saturating_add(1),
            (true, false) => ok_err = ok_err.saturating_add(1),
            (false, true) => err_ok = err_ok.saturating_add(1),
        }

        rows.push((case, cpp, rust));
    }

    let mut out = String::new();
    writeln!(
        &mut out,
        "# Phase 4 Corpus C++ vs Rust Status Differential Report (Auto-generated)"
    )?;
    writeln!(&mut out)?;
    writeln!(
        &mut out,
        "Generated by: `cargo run -p xtask -- corpus-status-report`"
    )?;
    writeln!(&mut out)?;
    writeln!(&mut out, "## Inputs")?;
    writeln!(&mut out, "- Corpus: `tests/corpus/*.dsp`")?;
    writeln!(&mut out, "- C++ binary: `{}`", cpp_bin.display())?;
    if cpp_bin_is_fallback {
        writeln!(
            &mut out,
            "- Note: fallback to `faust` from PATH because `{}/build/bin/faust` was not found.",
            CPP_SOURCE_ROOT
        )?;
        writeln!(
            &mut out,
            "- Action: set `FAUST_CPP_BIN` explicitly to the source-of-truth C++ binary when available."
        )?;
    }
    writeln!(
        &mut out,
        "- Rust path: `compiler::Compiler::compile_file_default_to_signals`"
    )?;
    writeln!(&mut out)?;
    writeln!(&mut out, "## Summary")?;
    writeln!(&mut out, "- Total cases: `{total}`")?;
    writeln!(&mut out, "- `OK/OK`: `{ok_ok}`")?;
    writeln!(&mut out, "- `ERR/ERR`: `{err_err}`")?;
    writeln!(&mut out, "- `OK/ERR` (C++ ok, Rust err): `{ok_err}`")?;
    writeln!(&mut out, "- `ERR/OK` (C++ err, Rust ok): `{err_ok}`")?;
    writeln!(&mut out)?;

    writeln!(&mut out, "## Parity Mismatches")?;
    writeln!(
        &mut out,
        "| Case | Class | C++ | Rust stage | Rust reason | C++ reason |"
    )?;
    writeln!(
        &mut out,
        "|------|-------|-----|------------|-------------|------------|"
    )?;
    for (case, cpp, rust) in &rows {
        let class = match (cpp.ok, rust.ok) {
            (true, false) => "OK/ERR",
            (false, true) => "ERR/OK",
            _ => continue,
        };
        writeln!(
            &mut out,
            "| `{}` | `{}` | `{}` | `{}` | `{}` | `{}` |",
            case,
            class,
            status_cell(cpp),
            rust.stage,
            markdown_escape(&rust.reason),
            markdown_escape(&cpp.reason),
        )?;
    }
    writeln!(&mut out)?;

    writeln!(&mut out, "## Full Matrix")?;
    writeln!(&mut out, "| Case | C++ | Rust | Rust stage | Rust reason |")?;
    writeln!(&mut out, "|------|-----|------|------------|-------------|")?;
    for (case, cpp, rust) in &rows {
        writeln!(
            &mut out,
            "| `{}` | `{}` | `{}` | `{}` | `{}` |",
            case,
            status_cell(cpp),
            status_cell(rust),
            rust.stage,
            markdown_escape(&rust.reason),
        )?;
    }
    writeln!(&mut out)?;
    writeln!(&mut out, "## Next Actions")?;
    writeln!(
        &mut out,
        "- Treat all `OK/ERR` and `ERR/OK` rows as parity tasks in parser/eval/propagate."
    )?;
    writeln!(
        &mut out,
        "- Re-run this report after each parity fix touching `tests/corpus` behavior."
    )?;

    if let Some(parent) = report_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&report_path, out)?;
    println!("updated {}", report_path.display());
    Ok(())
}

#[derive(Clone, Debug, PartialEq, Eq)]
/// Reduced shell signature extracted from generated C++ backend text.
///
/// The report uses this instead of full-text diffing so parity checks stay
/// stable while inner statement lowering is still evolving.
pub(crate) struct ShellSignature {
    faustclass: Option<String>,
    class_decl: Option<String>,
    has_restrict_define: bool,
    has_exp10_aliases: bool,
}

#[derive(Clone, Debug)]
/// One row in a backend differential report table.
pub(crate) struct CppDiffRow {
    case: String,
    class: &'static str,
    rust_reason: String,
    cpp_reason: String,
}

#[derive(Clone, Debug, PartialEq, Eq)]
/// Reduced shell signature extracted from generated C backend text.
pub(crate) struct CShellSignature {
    has_typedef_struct: bool,
    has_faustfloat_define: bool,
    has_restrict_define: bool,
    has_instance_constants_fn: bool,
    has_instance_reset_ui_fn: bool,
    has_instance_clear_fn: bool,
    has_instance_init_fn: bool,
    has_build_ui_fn: bool,
    has_compute_fn: bool,
    has_instance_init_ordered_calls: bool,
}

/// Regenerates the representative C++ backend shell-signature diff report.
pub(crate) fn cpp_backend_diff_report() -> Result<(), Box<dyn std::error::Error>> {
    let root = workspace_root();
    let report_path = root.join(CPP_BACKEND_DIFF_REPORT_REL_PATH);
    let compiler = compiler::Compiler::new();
    let (cpp_bin, cpp_bin_is_fallback) = resolve_cpp_faust_bin();
    let options = codegen::backends::cpp::CppOptions {
        class_name: Some("mydsp".to_owned()),
        ..codegen::backends::cpp::CppOptions::default()
    };

    let representative = [
        "rep_01_passthrough.dsp",
        "rep_05_one_pole_lowpass.dsp",
        "rep_09_ui_slider.dsp",
        "rep_17_ui_groups.dsp",
        "rep_20_environment_waveform.dsp",
        "rep_22_parallel_mix.dsp",
        "rep_28_nested_ui_groups.dsp",
        "rep_31_extended_primitives.dsp",
    ];

    let mut rows = Vec::with_capacity(representative.len());
    let mut ok = 0usize;
    let mut diff = 0usize;
    let mut unsupported = 0usize;

    for case in representative {
        let path = root.join("tests").join("corpus").join(case);
        let rust_output = compiler.compile_file_default_to_cpp(&path, &options);
        let cpp_output = Command::new(&cpp_bin).arg(&path).output();

        let row = match (rust_output, cpp_output) {
            (Ok(_), Err(err)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: "Rust path ok".to_owned(),
                    cpp_reason: format!("cannot run `{}`: {err}", cpp_bin.display()),
                }
            }
            (Err(err), Err(cpp_err)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: format!("cannot run `{}`: {cpp_err}", cpp_bin.display()),
                }
            }
            (Ok(rust_text), Ok(cpp_output)) if cpp_output.status.success() => {
                let cpp_text = String::from_utf8(cpp_output.stdout)?;
                let rust_sig = extract_shell_signature(&rust_text);
                let cpp_sig = extract_shell_signature(&cpp_text);
                if rust_sig == cpp_sig {
                    ok = ok.saturating_add(1);
                    CppDiffRow {
                        case: case.to_owned(),
                        class: "OK",
                        rust_reason: "shell signature matches".to_owned(),
                        cpp_reason: "ok".to_owned(),
                    }
                } else {
                    diff = diff.saturating_add(1);
                    CppDiffRow {
                        case: case.to_owned(),
                        class: "DIFF",
                        rust_reason: format!("rust={rust_sig:?}"),
                        cpp_reason: format!("cpp={cpp_sig:?}"),
                    }
                }
            }
            (Ok(_), Ok(cpp_output)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: "Rust path ok".to_owned(),
                    cpp_reason: first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stderr))
                        .or_else(|| {
                            first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stdout))
                        })
                        .unwrap_or_else(|| format!("failed with status {}", cpp_output.status)),
                }
            }
            (Err(err), Ok(cpp_output)) if cpp_output.status.success() => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: "C++ path ok".to_owned(),
                }
            }
            (Err(err), Ok(cpp_output)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stderr))
                        .or_else(|| {
                            first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stdout))
                        })
                        .unwrap_or_else(|| format!("failed with status {}", cpp_output.status)),
                }
            }
        };
        rows.push(row);
    }

    let mut out = String::new();
    writeln!(
        &mut out,
        "# Phase 6 C++ Backend Differential Report (Module-First, Shell-Normalized)"
    )?;
    writeln!(&mut out)?;
    writeln!(
        &mut out,
        "Generated by: `cargo run -p xtask -- cpp-backend-diff-report`"
    )?;
    writeln!(&mut out, "- C++ binary: `{}`", cpp_bin.display())?;
    if cpp_bin_is_fallback {
        writeln!(
            &mut out,
            "- Note: fallback to `faust` from PATH because `{}/build/bin/faust` was not found.",
            CPP_SOURCE_ROOT
        )?;
    }
    writeln!(
        &mut out,
        "- Normalization: compare module-shell signature only"
    )?;
    writeln!(&mut out, "  - `#define FAUSTCLASS <name>`")?;
    writeln!(&mut out, "  - `class <name> : public dsp`")?;
    writeln!(
        &mut out,
        "  - presence of `RESTRICT` and Apple `exp10` aliases"
    )?;
    writeln!(&mut out)?;
    writeln!(&mut out, "## Summary")?;
    writeln!(&mut out, "- Cases: `{}`", rows.len())?;
    writeln!(&mut out, "- `OK`: `{ok}`")?;
    writeln!(&mut out, "- `DIFF`: `{diff}`")?;
    writeln!(&mut out, "- `UNSUPPORTED`: `{unsupported}`")?;
    writeln!(&mut out)?;
    writeln!(
        &mut out,
        "| Case | Status | Rust detail | C++ detail |\n|------|--------|-------------|------------|"
    )?;
    for row in &rows {
        writeln!(
            &mut out,
            "| `{}` | `{}` | `{}` | `{}` |",
            row.case,
            row.class,
            markdown_escape(&row.rust_reason),
            markdown_escape(&row.cpp_reason)
        )?;
    }
    writeln!(&mut out)?;
    writeln!(&mut out, "## Notes")?;
    writeln!(
        &mut out,
        "- This report tracks module-shell parity while full production signal->FIR lowering is still in progress."
    )?;
    writeln!(
        &mut out,
        "- `DIFF` rows are expected to shrink as statement/value lowering and orchestration parity advance."
    )?;

    if let Some(parent) = report_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&report_path, out)?;
    println!("updated {}", report_path.display());
    Ok(())
}

/// Regenerates the representative table fast-lane parity report.
pub(crate) fn table_fastlane_diff_report() -> Result<(), Box<dyn std::error::Error>> {
    let root = workspace_root();
    let report_path = root.join(TABLE_FASTLANE_DIFF_REPORT_REL_PATH);
    let compiler = compiler::Compiler::new();
    let (cpp_bin, cpp_bin_is_fallback) = resolve_cpp_faust_bin();
    let options = codegen::backends::cpp::CppOptions {
        class_name: Some("mydsp".to_owned()),
        ..codegen::backends::cpp::CppOptions::default()
    };

    let representative = [
        "rep_20_environment_waveform.dsp",
        "rep_30_environment_access_pair.dsp",
        "rep_34_table_rdtable_readonly_const.dsp",
        "rep_35_table_rwtable_runtime_write.dsp",
        "rep_36_table_rdtable_negative_index.dsp",
        "rep_37_table_rwtable_negative_indices.dsp",
    ];

    let mut rows = Vec::with_capacity(representative.len());
    let mut ok = 0usize;
    let mut diff = 0usize;
    let mut unsupported = 0usize;

    for case in representative {
        let path = root.join("tests").join("corpus").join(case);
        let rust_output = compiler.compile_file_default_to_cpp_with_lane(
            &path,
            &options,
            compiler::SignalFirLane::TransformFastLane,
        );
        let cpp_output = Command::new(&cpp_bin).arg(&path).output();

        let row = match (rust_output, cpp_output) {
            (Ok(_), Err(err)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: "Rust fast-lane ok".to_owned(),
                    cpp_reason: format!("cannot run `{}`: {err}", cpp_bin.display()),
                }
            }
            (Err(err), Err(cpp_err)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: format!("cannot run `{}`: {cpp_err}", cpp_bin.display()),
                }
            }
            (Ok(rust_text), Ok(cpp_output)) if cpp_output.status.success() => {
                let cpp_text = String::from_utf8(cpp_output.stdout)?;
                let rust_sig = extract_shell_signature(&rust_text);
                let cpp_sig = extract_shell_signature(&cpp_text);
                if rust_sig == cpp_sig {
                    ok = ok.saturating_add(1);
                    CppDiffRow {
                        case: case.to_owned(),
                        class: "OK",
                        rust_reason: "shell signature matches".to_owned(),
                        cpp_reason: "ok".to_owned(),
                    }
                } else {
                    diff = diff.saturating_add(1);
                    CppDiffRow {
                        case: case.to_owned(),
                        class: "DIFF",
                        rust_reason: format!("rust={rust_sig:?}"),
                        cpp_reason: format!("cpp={cpp_sig:?}"),
                    }
                }
            }
            (Ok(_), Ok(cpp_output)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: "Rust fast-lane ok".to_owned(),
                    cpp_reason: first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stderr))
                        .or_else(|| {
                            first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stdout))
                        })
                        .unwrap_or_else(|| format!("failed with status {}", cpp_output.status)),
                }
            }
            (Err(err), Ok(cpp_output)) if cpp_output.status.success() => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: "C++ path ok".to_owned(),
                }
            }
            (Err(err), Ok(cpp_output)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stderr))
                        .or_else(|| {
                            first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stdout))
                        })
                        .unwrap_or_else(|| format!("failed with status {}", cpp_output.status)),
                }
            }
        };
        rows.push(row);
    }

    let mut out = String::new();
    writeln!(
        &mut out,
        "# Phase 6 Table Fast-Lane Differential Report (C++ vs Rust)"
    )?;
    writeln!(&mut out)?;
    writeln!(
        &mut out,
        "Generated by: `cargo run -p xtask -- table-fastlane-diff-report`"
    )?;
    writeln!(&mut out, "- C++ binary: `{}`", cpp_bin.display())?;
    if cpp_bin_is_fallback {
        writeln!(
            &mut out,
            "- Note: fallback to `faust` from PATH because `{}/build/bin/faust` was not found.",
            CPP_SOURCE_ROOT
        )?;
    }
    writeln!(
        &mut out,
        "- Rust route: `compiler::SignalFirLane::TransformFastLane`"
    )?;
    writeln!(&mut out)?;
    writeln!(&mut out, "## Summary")?;
    writeln!(&mut out, "- Cases: `{}`", rows.len())?;
    writeln!(&mut out, "- `OK`: `{ok}`")?;
    writeln!(&mut out, "- `DIFF`: `{diff}`")?;
    writeln!(&mut out, "- `UNSUPPORTED`: `{unsupported}`")?;
    writeln!(&mut out)?;
    writeln!(
        &mut out,
        "| Case | Status | Rust detail | C++ detail |\n|------|--------|-------------|------------|"
    )?;
    for row in &rows {
        writeln!(
            &mut out,
            "| `{}` | `{}` | `{}` | `{}` |",
            row.case,
            row.class,
            markdown_escape(&row.rust_reason),
            markdown_escape(&row.cpp_reason)
        )?;
    }
    writeln!(&mut out)?;
    writeln!(&mut out, "## Notes")?;
    writeln!(
        &mut out,
        "- Comparison is shell-signature based (`FAUSTCLASS`, class declaration, macro aliases)."
    )?;
    writeln!(
        &mut out,
        "- This report focuses on table-oriented fixtures for Step 2J closure."
    )?;

    if let Some(parent) = report_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&report_path, out)?;
    println!("updated {}", report_path.display());
    Ok(())
}

/// Regenerates the representative C fast-lane shell-signature diff report.
pub(crate) fn c_fastlane_diff_report() -> Result<(), Box<dyn std::error::Error>> {
    let root = workspace_root();
    let report_path = root.join(C_FASTLANE_DIFF_REPORT_REL_PATH);
    let compiler = compiler::Compiler::new();
    let (cpp_bin, cpp_bin_is_fallback) = resolve_cpp_faust_bin();
    let options = codegen::backends::c::COptions {
        class_name: Some("mydsp".to_owned()),
        ..codegen::backends::c::COptions::default()
    };

    let representative = [
        "rep_01_passthrough.dsp",
        "rep_05_one_pole_lowpass.dsp",
        "rep_07_nonlinear_clip.dsp",
        "rep_09_ui_slider.dsp",
        "rep_10_two_in_two_out_ui.dsp",
        "rep_17_ui_groups.dsp",
        "rep_20_environment_waveform.dsp",
        "rep_22_parallel_mix.dsp",
        "rep_23_feedback_simple.dsp",
        "rep_28_nested_ui_groups.dsp",
        "rep_30_environment_access_pair.dsp",
        "rep_31_extended_primitives.dsp",
        "rep_34_table_rdtable_readonly_const.dsp",
        "rep_35_table_rwtable_runtime_write.dsp",
        "rep_36_table_rdtable_negative_index.dsp",
        "rep_37_table_rwtable_negative_indices.dsp",
    ];

    let mut rows = Vec::with_capacity(representative.len());
    let mut ok = 0usize;
    let mut diff = 0usize;
    let mut unsupported = 0usize;

    for case in representative {
        let path = root.join("tests").join("corpus").join(case);
        let rust_output = compiler.compile_file_default_to_c_with_lane(
            &path,
            &options,
            compiler::SignalFirLane::TransformFastLane,
        );
        let cpp_output = Command::new(&cpp_bin)
            .arg(&path)
            .arg("-lang")
            .arg("c")
            .arg("-cn")
            .arg("mydsp")
            .output();

        let row = match (rust_output, cpp_output) {
            (Ok(_), Err(err)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: "Rust C fast-lane ok".to_owned(),
                    cpp_reason: format!("cannot run `{}`: {err}", cpp_bin.display()),
                }
            }
            (Err(err), Err(cpp_err)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: format!("cannot run `{}`: {cpp_err}", cpp_bin.display()),
                }
            }
            (Ok(rust_text), Ok(cpp_output)) if cpp_output.status.success() => {
                let cpp_text = String::from_utf8(cpp_output.stdout)?;
                let rust_sig = extract_c_shell_signature(&rust_text);
                let cpp_sig = extract_c_shell_signature(&cpp_text);
                if rust_sig == cpp_sig {
                    ok = ok.saturating_add(1);
                    CppDiffRow {
                        case: case.to_owned(),
                        class: "OK",
                        rust_reason: "C shell signature matches".to_owned(),
                        cpp_reason: "ok".to_owned(),
                    }
                } else {
                    diff = diff.saturating_add(1);
                    CppDiffRow {
                        case: case.to_owned(),
                        class: "DIFF",
                        rust_reason: format!("rust={rust_sig:?}"),
                        cpp_reason: format!("cpp={cpp_sig:?}"),
                    }
                }
            }
            (Ok(_), Ok(cpp_output)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: "Rust C fast-lane ok".to_owned(),
                    cpp_reason: first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stderr))
                        .or_else(|| {
                            first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stdout))
                        })
                        .unwrap_or_else(|| format!("failed with status {}", cpp_output.status)),
                }
            }
            (Err(err), Ok(cpp_output)) if cpp_output.status.success() => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: "C++ C backend path ok".to_owned(),
                }
            }
            (Err(err), Ok(cpp_output)) => {
                unsupported = unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.to_owned(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stderr))
                        .or_else(|| {
                            first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stdout))
                        })
                        .unwrap_or_else(|| format!("failed with status {}", cpp_output.status)),
                }
            }
        };
        rows.push(row);
    }

    let mut out = String::new();
    writeln!(
        &mut out,
        "# Phase 6 C Fast-Lane Differential Report (C++ `-lang c` vs Rust)"
    )?;
    writeln!(&mut out)?;
    writeln!(
        &mut out,
        "Generated by: `cargo run -p xtask -- c-fastlane-diff-report`"
    )?;
    writeln!(&mut out, "- C++ binary: `{}`", cpp_bin.display())?;
    if cpp_bin_is_fallback {
        writeln!(
            &mut out,
            "- Note: fallback to `faust` from PATH because `{}/build/bin/faust` was not found.",
            CPP_SOURCE_ROOT
        )?;
    }
    writeln!(
        &mut out,
        "- C++ command: `faust <case>.dsp -lang c -cn mydsp`"
    )?;
    writeln!(
        &mut out,
        "- Rust route: `compiler::SignalFirLane::TransformFastLane` + `--dump-c`"
    )?;
    writeln!(&mut out)?;
    writeln!(&mut out, "## Summary")?;
    writeln!(&mut out, "- Cases: `{}`", rows.len())?;
    writeln!(&mut out, "- `OK`: `{ok}`")?;
    writeln!(&mut out, "- `DIFF`: `{diff}`")?;
    writeln!(&mut out, "- `UNSUPPORTED`: `{unsupported}`")?;
    writeln!(&mut out)?;
    writeln!(
        &mut out,
        "| Case | Status | Rust detail | C++ detail |\n|------|--------|-------------|------------|"
    )?;
    for row in &rows {
        writeln!(
            &mut out,
            "| `{}` | `{}` | `{}` | `{}` |",
            row.case,
            row.class,
            markdown_escape(&row.rust_reason),
            markdown_escape(&row.cpp_reason)
        )?;
    }
    writeln!(&mut out)?;
    writeln!(&mut out, "## Notes")?;
    writeln!(
        &mut out,
        "- Comparison is C-shell signature based (typedef/defines/lifecycle/UI/compute function presence and init call ordering)."
    )?;
    writeln!(
        &mut out,
        "- This report is the Step 7B guardrail for C fast-lane parity progression."
    )?;

    if let Some(parent) = report_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&report_path, out)?;
    println!("updated {}", report_path.display());
    Ok(())
}

/// Regenerates the full-corpus C/C++ backend fast-lane differential report.
pub(crate) fn backend_full_corpus_diff_report() -> Result<(), Box<dyn std::error::Error>> {
    let root = workspace_root();
    let report_path = root.join(BACKEND_FULL_CORPUS_DIFF_REPORT_REL_PATH);
    let compiler = compiler::Compiler::new();
    let (cpp_bin, cpp_bin_is_fallback) = resolve_cpp_faust_bin();
    let files = corpus_files()?;
    let cpp_options = codegen::backends::cpp::CppOptions {
        class_name: Some("mydsp".to_owned()),
        ..codegen::backends::cpp::CppOptions::default()
    };
    let c_options = codegen::backends::c::COptions {
        class_name: Some("mydsp".to_owned()),
        ..codegen::backends::c::COptions::default()
    };

    let mut cpp_rows = Vec::with_capacity(files.len());
    let mut cpp_ok = 0usize;
    let mut cpp_diff = 0usize;
    let mut cpp_unsupported = 0usize;

    let mut c_rows = Vec::with_capacity(files.len());
    let mut c_ok = 0usize;
    let mut c_diff = 0usize;
    let mut c_unsupported = 0usize;

    for file in &files {
        let case = case_name(file)?;

        let rust_cpp = compiler.compile_file_default_to_cpp_with_lane(
            file,
            &cpp_options,
            compiler::SignalFirLane::TransformFastLane,
        );
        let cpp_cpp = Command::new(&cpp_bin)
            .arg(file)
            .arg("-lang")
            .arg("cpp")
            .arg("-cn")
            .arg("mydsp")
            .output();
        let cpp_row = match (rust_cpp, cpp_cpp) {
            (Ok(_), Err(err)) => {
                cpp_unsupported = cpp_unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.clone(),
                    class: "UNSUPPORTED",
                    rust_reason: "Rust C++ fast-lane ok".to_owned(),
                    cpp_reason: format!("cannot run `{}`: {err}", cpp_bin.display()),
                }
            }
            (Err(err), Err(cpp_err)) => {
                cpp_unsupported = cpp_unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.clone(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: format!("cannot run `{}`: {cpp_err}", cpp_bin.display()),
                }
            }
            (Ok(rust_text), Ok(cpp_output)) if cpp_output.status.success() => {
                let cpp_text = String::from_utf8(cpp_output.stdout)?;
                let rust_sig = extract_shell_signature(&rust_text);
                let cpp_sig = extract_shell_signature(&cpp_text);
                if rust_sig == cpp_sig {
                    cpp_ok = cpp_ok.saturating_add(1);
                    CppDiffRow {
                        case: case.clone(),
                        class: "OK",
                        rust_reason: "shell signature matches".to_owned(),
                        cpp_reason: "ok".to_owned(),
                    }
                } else {
                    cpp_diff = cpp_diff.saturating_add(1);
                    CppDiffRow {
                        case: case.clone(),
                        class: "DIFF",
                        rust_reason: format!("rust={rust_sig:?}"),
                        cpp_reason: format!("cpp={cpp_sig:?}"),
                    }
                }
            }
            (Ok(_), Ok(cpp_output)) => {
                cpp_unsupported = cpp_unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.clone(),
                    class: "UNSUPPORTED",
                    rust_reason: "Rust C++ fast-lane ok".to_owned(),
                    cpp_reason: first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stderr))
                        .or_else(|| {
                            first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stdout))
                        })
                        .unwrap_or_else(|| format!("failed with status {}", cpp_output.status)),
                }
            }
            (Err(err), Ok(cpp_output)) if cpp_output.status.success() => {
                cpp_unsupported = cpp_unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.clone(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: "C++ reference path ok".to_owned(),
                }
            }
            (Err(err), Ok(cpp_output)) => {
                cpp_unsupported = cpp_unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.clone(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stderr))
                        .or_else(|| {
                            first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stdout))
                        })
                        .unwrap_or_else(|| format!("failed with status {}", cpp_output.status)),
                }
            }
        };
        cpp_rows.push(cpp_row);

        let rust_c = compiler.compile_file_default_to_c_with_lane(
            file,
            &c_options,
            compiler::SignalFirLane::TransformFastLane,
        );
        let cpp_c = Command::new(&cpp_bin)
            .arg(file)
            .arg("-lang")
            .arg("c")
            .arg("-cn")
            .arg("mydsp")
            .output();
        let c_row = match (rust_c, cpp_c) {
            (Ok(_), Err(err)) => {
                c_unsupported = c_unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.clone(),
                    class: "UNSUPPORTED",
                    rust_reason: "Rust C fast-lane ok".to_owned(),
                    cpp_reason: format!("cannot run `{}`: {err}", cpp_bin.display()),
                }
            }
            (Err(err), Err(cpp_err)) => {
                c_unsupported = c_unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.clone(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: format!("cannot run `{}`: {cpp_err}", cpp_bin.display()),
                }
            }
            (Ok(rust_text), Ok(cpp_output)) if cpp_output.status.success() => {
                let cpp_text = String::from_utf8(cpp_output.stdout)?;
                let rust_sig = extract_c_shell_signature(&rust_text);
                let cpp_sig = extract_c_shell_signature(&cpp_text);
                if rust_sig == cpp_sig {
                    c_ok = c_ok.saturating_add(1);
                    CppDiffRow {
                        case: case.clone(),
                        class: "OK",
                        rust_reason: "C shell signature matches".to_owned(),
                        cpp_reason: "ok".to_owned(),
                    }
                } else {
                    c_diff = c_diff.saturating_add(1);
                    CppDiffRow {
                        case: case.clone(),
                        class: "DIFF",
                        rust_reason: format!("rust={rust_sig:?}"),
                        cpp_reason: format!("cpp={cpp_sig:?}"),
                    }
                }
            }
            (Ok(_), Ok(cpp_output)) => {
                c_unsupported = c_unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.clone(),
                    class: "UNSUPPORTED",
                    rust_reason: "Rust C fast-lane ok".to_owned(),
                    cpp_reason: first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stderr))
                        .or_else(|| {
                            first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stdout))
                        })
                        .unwrap_or_else(|| format!("failed with status {}", cpp_output.status)),
                }
            }
            (Err(err), Ok(cpp_output)) if cpp_output.status.success() => {
                c_unsupported = c_unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.clone(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: "C reference path ok".to_owned(),
                }
            }
            (Err(err), Ok(cpp_output)) => {
                c_unsupported = c_unsupported.saturating_add(1);
                CppDiffRow {
                    case: case.clone(),
                    class: "UNSUPPORTED",
                    rust_reason: err.to_string(),
                    cpp_reason: first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stderr))
                        .or_else(|| {
                            first_non_empty_line(&String::from_utf8_lossy(&cpp_output.stdout))
                        })
                        .unwrap_or_else(|| format!("failed with status {}", cpp_output.status)),
                }
            }
        };
        c_rows.push(c_row);
    }

    let mut out = String::new();
    writeln!(
        &mut out,
        "# Phase 6 Backend Full-Corpus Differential Report (Rust fast-lane vs C++ reference)"
    )?;
    writeln!(&mut out)?;
    writeln!(
        &mut out,
        "Generated by: `cargo run -p xtask -- backend-full-corpus-diff-report`"
    )?;
    writeln!(&mut out, "- C++ binary: `{}`", cpp_bin.display())?;
    if cpp_bin_is_fallback {
        writeln!(
            &mut out,
            "- Note: fallback to `faust` from PATH because `{}/build/bin/faust` was not found.",
            CPP_SOURCE_ROOT
        )?;
    }
    writeln!(&mut out, "- Corpus: `tests/corpus/*.dsp`")?;
    writeln!(
        &mut out,
        "- Rust route: `compiler::SignalFirLane::TransformFastLane`"
    )?;
    writeln!(&mut out)?;
    writeln!(&mut out, "## Summary")?;
    writeln!(&mut out, "- Cases: `{}`", files.len())?;
    writeln!(
        &mut out,
        "- C++ backend parity: `OK={cpp_ok}` `DIFF={cpp_diff}` `UNSUPPORTED={cpp_unsupported}`"
    )?;
    writeln!(
        &mut out,
        "- C backend parity: `OK={c_ok}` `DIFF={c_diff}` `UNSUPPORTED={c_unsupported}`"
    )?;
    writeln!(&mut out)?;

    writeln!(&mut out, "## C++ Backend Matrix")?;
    writeln!(
        &mut out,
        "| Case | Status | Rust detail | C++ detail |\n|------|--------|-------------|------------|"
    )?;
    for row in &cpp_rows {
        writeln!(
            &mut out,
            "| `{}` | `{}` | `{}` | `{}` |",
            row.case,
            row.class,
            markdown_escape(&row.rust_reason),
            markdown_escape(&row.cpp_reason)
        )?;
    }
    writeln!(&mut out)?;

    writeln!(&mut out, "## C Backend Matrix")?;
    writeln!(
        &mut out,
        "| Case | Status | Rust detail | C++ detail |\n|------|--------|-------------|------------|"
    )?;
    for row in &c_rows {
        writeln!(
            &mut out,
            "| `{}` | `{}` | `{}` | `{}` |",
            row.case,
            row.class,
            markdown_escape(&row.rust_reason),
            markdown_escape(&row.cpp_reason)
        )?;
    }
    writeln!(&mut out)?;
    writeln!(&mut out, "## Notes")?;
    writeln!(
        &mut out,
        "- C++ reference command: `faust <case>.dsp -lang cpp -cn mydsp` (shell-signature metric)."
    )?;
    writeln!(
        &mut out,
        "- C reference command: `faust <case>.dsp -lang c -cn mydsp` (C-shell-signature metric)."
    )?;

    if let Some(parent) = report_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(&report_path, out)?;
    println!("updated {}", report_path.display());
    Ok(())
}

/// Extracts the normalized C++ backend shell signature from emitted source text.
pub(crate) fn extract_shell_signature(text: &str) -> ShellSignature {
    let mut faustclass = None::<String>;
    let mut class_decl = None::<String>;
    let mut has_restrict_define = false;
    let mut has_exp10f_alias = false;
    let mut has_exp10_alias = false;

    for raw in text.lines() {
        let line = raw.trim();
        if let Some(rest) = line.strip_prefix("#define FAUSTCLASS ") {
            faustclass = Some(rest.trim().to_owned());
        }
        if let Some(rest) = line.strip_prefix("class ")
            && let Some((name, _)) = rest.split_once(" : public dsp")
        {
            class_decl = Some(name.trim().to_owned());
        }
        if line.contains("#define RESTRICT") {
            has_restrict_define = true;
        }
        if line == "#define exp10f __exp10f" {
            has_exp10f_alias = true;
        }
        if line == "#define exp10 __exp10" {
            has_exp10_alias = true;
        }
    }

    ShellSignature {
        faustclass,
        class_decl,
        has_restrict_define,
        has_exp10_aliases: has_exp10f_alias && has_exp10_alias,
    }
}

/// Extracts the normalized C backend shell signature from emitted source text.
pub(crate) fn extract_c_shell_signature(text: &str) -> CShellSignature {
    let has_typedef_struct = text.contains("typedef struct {");
    let has_faustfloat_define = text.contains("#ifndef FAUSTFLOAT");
    let has_restrict_define = text.contains("#define RESTRICT");
    let has_instance_constants_fn = text.contains("void instanceConstants");
    let has_instance_reset_ui_fn = text.contains("void instanceResetUserInterface");
    let has_instance_clear_fn = text.contains("void instanceClear");
    let has_instance_init_fn = text.contains("void instanceInit");
    let has_build_ui_fn = text.contains("void buildUserInterface");
    let has_compute_fn = text.contains("void compute");

    let has_instance_init_ordered_calls = has_ordered_instance_init_calls(text);

    CShellSignature {
        has_typedef_struct,
        has_faustfloat_define,
        has_restrict_define,
        has_instance_constants_fn,
        has_instance_reset_ui_fn,
        has_instance_clear_fn,
        has_instance_init_fn,
        has_build_ui_fn,
        has_compute_fn,
        has_instance_init_ordered_calls,
    }
}

/// Detects the canonical `instanceInit` call ordering in generated C output.
pub(crate) fn has_ordered_instance_init_calls(text: &str) -> bool {
    let mut search_from = 0usize;
    while let Some(rel) = text[search_from..].find("void instanceInit") {
        let start = search_from + rel;
        let tail = &text[start..];
        let end = tail.find("}\n").unwrap_or(tail.len());
        let body = &tail[..end];
        let c_i = body.find("instanceConstants");
        let r_i = body.find("instanceResetUserInterface");
        let cl_i = body.find("instanceClear");
        if matches!((c_i, r_i, cl_i), (Some(a), Some(b), Some(c)) if a < b && b < c) {
            return true;
        }
        search_from = start + "void instanceInit".len();
    }
    false
}

/// Resolves the preferred C++ reference compiler path for report workflows.
///
/// Returns `(path, used_fallback)` where `used_fallback` records whether the
/// helper had to fall back to `faust` from `PATH`.
pub(crate) fn resolve_cpp_faust_bin() -> (PathBuf, bool) {
    if let Some(path) = std::env::var_os("FAUST_CPP_BIN") {
        return (PathBuf::from(path), false);
    }
    let built = Path::new(CPP_SOURCE_ROOT).join("build/bin/faust");
    if built.exists() {
        return (built, false);
    }
    (PathBuf::from("faust"), true)
}

/// Runs one DSP through the C++ reference compiler and summarizes the outcome.
pub(crate) fn cpp_case_status(
    cpp_bin: &Path,
    input: &Path,
) -> Result<CaseStatus, Box<dyn std::error::Error>> {
    let status = Command::new(cpp_bin)
        .arg(input)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status()?;
    if status.success() {
        return Ok(CaseStatus {
            ok: true,
            stage: "ok",
            reason: "ok".to_owned(),
        });
    }

    let output = Command::new(cpp_bin).arg(input).output()?;
    let reason = first_non_empty_line(&String::from_utf8_lossy(&output.stderr))
        .or_else(|| first_non_empty_line(&String::from_utf8_lossy(&output.stdout)))
        .unwrap_or_else(|| format!("failed with status {}", output.status));
    Ok(CaseStatus {
        ok: false,
        stage: "error",
        reason,
    })
}

/// Runs one DSP through the Rust compile-to-signals path and summarizes the outcome.
pub(crate) fn rust_case_status(compiler: &compiler::Compiler, input: &Path) -> CaseStatus {
    match compiler.compile_file_default_to_signals(input) {
        Ok(_) => CaseStatus {
            ok: true,
            stage: "ok",
            reason: "ok".to_owned(),
        },
        Err(err) => {
            let (stage, reason) = match &err {
                compiler::CompilerError::Import(..) => ("import", err.to_string()),
                compiler::CompilerError::Parse { .. } => ("parse", err.to_string()),
                compiler::CompilerError::Eval { .. } => ("eval", err.to_string()),
                compiler::CompilerError::Propagate { .. } => ("propagate", err.to_string()),
                compiler::CompilerError::Type { .. } => ("type", err.to_string()),
                compiler::CompilerError::Transform { .. } => ("transform", err.to_string()),
                compiler::CompilerError::FirVerify { .. } => ("fir", err.to_string()),
                compiler::CompilerError::Codegen { .. } => ("codegen", err.to_string()),
                compiler::CompilerError::CodegenC { .. } => ("codegen", err.to_string()),
                compiler::CompilerError::CodegenJulia { .. } => ("codegen", err.to_string()),
                compiler::CompilerError::CodegenInterp { .. } => ("codegen", err.to_string()),
                compiler::CompilerError::CodegenWasm { .. } => ("codegen", err.to_string()),
                compiler::CompilerError::MissingRoot { .. } => ("parse", err.to_string()),
            };
            CaseStatus {
                ok: false,
                stage,
                reason,
            }
        }
    }
}

/// Returns the compact `OK` / `ERR` cell text used in Markdown tables.
pub(crate) fn status_cell(status: &CaseStatus) -> &'static str {
    if status.ok { "OK" } else { "ERR" }
}

/// Returns the first non-empty trimmed line from command output.
pub(crate) fn first_non_empty_line(text: &str) -> Option<String> {
    text.lines()
        .map(str::trim)
        .find(|line| !line.is_empty())
        .map(ToOwned::to_owned)
}

/// Escapes a string for safe embedding in one-cell Markdown tables.
pub(crate) fn markdown_escape(value: &str) -> String {
    value.replace('|', "\\|").replace(['\n', '\r'], " ")
}

/// Extracts declared token names from a yacc-style parser grammar.
pub(crate) fn extract_parser_tokens(source: &str) -> BTreeSet<String> {
    let mut set = BTreeSet::new();
    for line in source.lines() {
        let trimmed = line.trim_start();
        let rest = if let Some(rest) = trimmed.strip_prefix("%token") {
            rest
        } else if let Some(rest) = trimmed.strip_prefix("%left") {
            rest
        } else if let Some(rest) = trimmed.strip_prefix("%right") {
            rest
        } else if let Some(rest) = trimmed.strip_prefix("%nonassoc") {
            rest
        } else {
            continue;
        };
        let rest = rest.trim();
        for raw in rest.split_whitespace() {
            let part = raw.trim_matches(|c: char| c == ',' || c == ';');
            if part.starts_with('<') || part.starts_with("/*") || part.starts_with("//") {
                continue;
            }
            if is_token_name(part) {
                set.insert(part.to_owned());
            }
        }
    }
    set
}

/// Extracts nonterminal heads from the C++ yacc grammar body.
pub(crate) fn extract_cpp_nonterminals(source: &str) -> BTreeSet<String> {
    let mut set = BTreeSet::new();
    for line in grammar_section(source).lines() {
        let trimmed = line.trim_start();
        if trimmed.starts_with('%') || trimmed.starts_with('|') {
            continue;
        }
        let Some((head, _)) = trimmed.split_once(':') else {
            continue;
        };
        let head = head.trim();
        if is_ident_name(head) {
            set.insert(head.to_ascii_lowercase());
        }
    }
    set
}

/// Extracts nonterminal heads from the Rust grammar prototype body.
pub(crate) fn extract_rust_nonterminals(source: &str) -> BTreeSet<String> {
    let mut set = BTreeSet::new();
    for line in grammar_section(source).lines() {
        let trimmed = line.trim_start();
        let Some((head, _)) = trimmed.split_once("->") else {
            continue;
        };
        let head = head.trim();
        if is_ident_name(head) {
            set.insert(head.to_ascii_lowercase());
        }
    }
    set
}

/// Extracts declared lexer start states from a lex/flex source file.
pub(crate) fn extract_lexer_states(source: &str) -> BTreeSet<String> {
    let mut set = BTreeSet::new();
    for line in source.lines() {
        let trimmed = line.trim_start();
        let rest = if let Some(rest) = trimmed.strip_prefix("%x") {
            rest
        } else if let Some(rest) = trimmed.strip_prefix("%s") {
            rest
        } else {
            continue;
        };
        for state in rest.split_whitespace() {
            let state = state.trim_matches(|c: char| c == ';');
            if is_ident_name(state) {
                set.insert(state.to_ascii_lowercase());
            }
        }
    }
    set
}

/// Extracts token names emitted by the C++ lexer implementation.
pub(crate) fn extract_cpp_lexer_emitted_tokens(source: &str) -> BTreeSet<String> {
    let mut set = BTreeSet::new();
    for line in source.lines() {
        let mut rest = line;
        while let Some(idx) = rest.find("return ") {
            let after = &rest[idx + "return ".len()..];
            if let Some(token) = scan_token_name(after) {
                set.insert(token);
            }
            rest = &after[after.char_indices().nth(1).map_or(after.len(), |(i, _)| i)..];
        }
    }
    set
}

/// Extracts token names emitted by the Rust lexer prototype.
pub(crate) fn extract_rust_lexer_emitted_tokens(source: &str) -> BTreeSet<String> {
    let mut set = BTreeSet::new();
    for line in source.lines() {
        let chars: Vec<char> = line.chars().collect();
        let mut i = 0usize;
        while i < chars.len() {
            if chars[i] != '\'' {
                i += 1;
                continue;
            }
            let mut j = i + 1;
            while j < chars.len() && chars[j] != '\'' {
                j += 1;
            }
            if j >= chars.len() {
                break;
            }
            let candidate: String = chars[i + 1..j].iter().collect();
            if is_token_name(&candidate) {
                set.insert(candidate);
            }
            // Move one character forward so overlapping quotes are still discovered.
            i += 1;
        }
    }
    set
}

/// Returns the grammar body between the first two yacc `%%` markers.
pub(crate) fn grammar_section(source: &str) -> &str {
    let mut marks = source.match_indices("%%");
    let Some((first, _)) = marks.next() else {
        return source;
    };
    let Some((second, _)) = marks.next() else {
        return &source[first + 2..];
    };
    &source[first + 2..second]
}

/// Returns `true` when `s` matches the token naming convention used in reports.
pub(crate) fn is_token_name(s: &str) -> bool {
    let mut has_upper = false;
    for c in s.chars() {
        if c.is_ascii_uppercase() {
            has_upper = true;
        } else if !(c.is_ascii_digit() || c == '_') {
            return false;
        }
    }
    has_upper
}

/// Returns `true` when `s` is a simple ASCII identifier.
pub(crate) fn is_ident_name(s: &str) -> bool {
    let mut chars = s.chars();
    let Some(first) = chars.next() else {
        return false;
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return false;
    }
    chars.all(|c| c.is_ascii_alphanumeric() || c == '_')
}

/// Scans the first token-like identifier from a lexer `return ...` fragment.
pub(crate) fn scan_token_name(source: &str) -> Option<String> {
    let mut start = None;
    for (idx, c) in source.char_indices() {
        if c.is_ascii_uppercase() || c == '_' {
            start = Some(idx);
            break;
        }
    }
    let start = start?;
    let token: String = source[start..]
        .chars()
        .take_while(|c| c.is_ascii_uppercase() || c.is_ascii_digit() || *c == '_')
        .collect();
    if is_token_name(&token) {
        Some(token)
    } else {
        None
    }
}

/// Returns `left - right` as a sorted vector.
pub(crate) fn diff_sorted(left: &BTreeSet<String>, right: &BTreeSet<String>) -> Vec<String> {
    left.difference(right).cloned().collect()
}

/// Returns accepted Rust alias names for one C++ token name.
pub(crate) fn token_aliases(cpp_name: &str) -> &'static [&'static str] {
    match cpp_name {
        "VIRG" => &["PAR"],
        "LISTING" => &["BLST"],
        _ => &[],
    }
}

/// Returns accepted Rust alias names for one C++ nonterminal head.
pub(crate) fn nonterminal_aliases(cpp_name: &str) -> &'static [&'static str] {
    match cpp_name {
        "params" => &["paramlist"],
        "recinition" => &["recdefinition"],
        "ident" => &["identexpr"],
        "fun" => &["funname"],
        "string" => &["rawstring", "uqstring", "fstring"],
        "doc" => &["doccontent"],
        "doctxt" | "doceqn" | "docdgm" | "docmtd" | "doclst" | "docntc" => &["docelem"],
        "lstattrdef" => &["lstattr"],
        "lstattrval" => &["lstattrvalue"],
        "ffunction" | "fconst" | "fvariable" | "fpar" | "fseq" | "fsum" | "fprod" | "finputs"
        | "foutputs" | "fondemand" | "fupsampling" | "fdownsampling" | "button" | "checkbox"
        | "vslider" | "hslider" | "nentry" | "vgroup" | "hgroup" | "tgroup" | "vbargraph"
        | "hbargraph" | "soundfile" => &["primitive"],
        _ => &[],
    }
}

/// Splits missing names into alias-covered and unresolved subsets.
pub(crate) fn partition_with_aliases(
    missing_exact: &[String],
    rust_set: &BTreeSet<String>,
    aliases: impl Fn(&str) -> &'static [&'static str],
) -> (Vec<(String, Vec<String>)>, Vec<String>) {
    let mut covered = Vec::new();
    let mut unresolved = Vec::new();

    for item in missing_exact {
        let mapped_hits = aliases(item)
            .iter()
            .copied()
            .filter(|candidate| rust_set.contains(*candidate))
            .map(ToOwned::to_owned)
            .collect::<Vec<_>>();
        if mapped_hits.is_empty() {
            unresolved.push(item.clone());
        } else {
            covered.push((item.clone(), mapped_hits));
        }
    }
    (covered, unresolved)
}

/// Renders one Markdown bullet section for a report.
pub(crate) fn render_list(
    out: &mut String,
    title: &str,
    items: &[String],
) -> Result<(), std::fmt::Error> {
    writeln!(out, "### {title}")?;
    if items.is_empty() {
        writeln!(out, "- (none)")?;
    } else {
        for item in items {
            writeln!(out, "- `{item}`")?;
        }
    }
    Ok(())
}

/// Renders one Markdown section describing alias-covered mismatches.
pub(crate) fn render_alias_list(
    out: &mut String,
    title: &str,
    items: &[(String, Vec<String>)],
) -> Result<(), std::fmt::Error> {
    writeln!(out, "### {title}")?;
    if items.is_empty() {
        writeln!(out, "- (none)")?;
        return Ok(());
    }
    for (source, targets) in items {
        let mapped = targets
            .iter()
            .map(|v| format!("`{v}`"))
            .collect::<Vec<_>>()
            .join(", ");
        writeln!(out, "- `{source}` -> {mapped}")?;
    }
    Ok(())
}
