//! `interp-ffi` — C/C++ FFI export of the Faust FBC interpreter backend.
//!
//! # Overview
//! This crate exposes a C-compatible API mirroring the official Faust
//! interpreter headers:
//! - `interpreter-dsp-c.h` — pure C API (generated by cbindgen + `build.rs`)
//! - `interpreter-dsp.h` — C++ wrapper classes (manually written, in `include/`)
//!
//! Distribution artifacts are produced by the top-level `faust-ffi` crate,
//! which links this crate as an `rlib` alongside other backend FFI crates.
//!
//! # Modules
//! - [`types`] — opaque FFI wrapper types, UIGlue, MetaGlue.
//! - [`cache`] — global factory cache (SHA → pointer map).
//! - [`ui`] — UI / meta dispatch helpers.
//! - [`factory`] — factory `extern "C"` functions (bitcode I/O, cache ops).
//! - [`instance`] — instance `extern "C"` functions (lifecycle, compute).
//!
//! # Safety model
//! All `extern "C"` functions are `unsafe` on the caller side.  Null-pointer
//! checks are performed at each entry point.  The Rust allocator owns all
//! heap memory; the caller must use `freeCMemory` for returned C strings.

#![allow(unsafe_code)] // FFI requires raw pointer operations throughout

pub mod cache;
pub mod factory;
pub mod instance;
pub mod types;
pub mod ui;
