use std::collections::HashSet;
use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=FAUST_RS_EMBEDDED_LIB_ROOT");
    println!("cargo:rerun-if-env-changed=FAUST_RS_FAUSTLIBRARIES_ROOT");
    println!("cargo:rerun-if-env-changed=FAUST_LIB_PATH");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR should be set"));
    let out_file = out_dir.join("embedded_faust_libraries.rs");
    let roots = discover_library_roots();
    let libraries = collect_library_sources_from_roots(&roots)
        .expect("embedded Faust library scan should succeed");

    let mut out = String::new();
    out.push_str("// @generated by crates/wasm-ffi/build.rs\n");
    out.push_str(&format!(
        "pub(crate) const EMBEDDED_FAUST_LIB_ROOT: Option<&str> = {};\n",
        roots
            .first()
            .map(|path| format!("Some({:?})", path.display().to_string()))
            .unwrap_or_else(|| "None".to_owned())
    ));
    out.push_str("pub(crate) const EMBEDDED_FAUST_LIB_ROOTS: &[&str] = &[\n");
    for root in &roots {
        out.push_str(&format!("    {:?},\n", root.display().to_string()));
    }
    out.push_str("];\n");
    out.push_str("pub(crate) const EMBEDDED_FAUST_LIBRARIES: &[(&str, &str)] = &[\n");
    for (path, source) in libraries {
        out.push_str(&format!("    ({path:?}, {source:?}),\n"));
    }
    out.push_str("];\n");

    let mut file = fs::File::create(&out_file).expect("generated source file should be writable");
    file.write_all(out.as_bytes())
        .expect("generated source file should be writable");
}

fn discover_library_roots() -> Vec<PathBuf> {
    for env_name in ["FAUST_RS_EMBEDDED_LIB_ROOT", "FAUST_RS_FAUSTLIBRARIES_ROOT"] {
        if let Some(raw) = env::var_os(env_name) {
            let roots = valid_roots_from_os_paths(raw);
            if !roots.is_empty() {
                return roots;
            }
        }
    }

    if let Some(raw) = env::var_os("FAUST_LIB_PATH") {
        let roots = valid_roots_from_os_paths(raw);
        if !roots.is_empty() {
            return roots;
        }
    }

    ["/usr/local/share/faust", "/usr/share/faust"]
        .into_iter()
        .map(PathBuf::from)
        .find(|candidate| candidate.is_dir())
        .into_iter()
        .collect()
}

fn valid_roots_from_os_paths(raw: std::ffi::OsString) -> Vec<PathBuf> {
    let mut roots = Vec::new();
    let mut seen = HashSet::new();
    for candidate in env::split_paths(&raw) {
        if candidate.is_dir() && seen.insert(candidate.clone()) {
            roots.push(candidate);
        }
    }
    roots
}

fn collect_library_sources_from_roots(
    roots: &[PathBuf],
) -> Result<Vec<(String, String)>, std::io::Error> {
    let mut out = Vec::new();
    let mut seen = HashSet::new();
    for root in roots {
        for (logical, source) in collect_library_sources(root)? {
            if seen.insert(logical.clone()) {
                out.push((logical, source));
            }
        }
    }
    out.sort_by(|(left, _), (right, _)| left.cmp(right));
    Ok(out)
}

fn collect_library_sources(root: &Path) -> Result<Vec<(String, String)>, std::io::Error> {
    let mut files = Vec::new();
    collect_library_files(root, root, &mut files)?;
    // Mirror the C++ faust wasmlib packaging, which flattens
    // `libraries/*.lib`, `libraries/dx7/*.lib`, and `libraries/old/*.lib`
    // into one directory: alias dx7/ and old/ entries under their bare file
    // names so for example `library("dx7.lib")` (used by stdfaust's `dx`
    // environment) resolves. Top-level names win on collision; other
    // subdirectories (for example `unsupported/`) are intentionally not
    // flattened.
    let mut aliases: Vec<(String, String)> = Vec::new();
    for (logical, source) in &files {
        let Some((dir, bare)) = logical.split_once('/') else {
            continue;
        };
        if !matches!(dir, "dx7" | "old") || bare.contains('/') {
            continue;
        }
        if !files.iter().any(|(existing, _)| existing == bare)
            && !aliases.iter().any(|(existing, _)| existing == bare)
        {
            aliases.push((bare.to_owned(), source.clone()));
        }
    }
    files.extend(aliases);
    files.sort_by(|(left, _), (right, _)| left.cmp(right));
    Ok(files)
}

fn collect_library_files(
    root: &Path,
    dir: &Path,
    out: &mut Vec<(String, String)>,
) -> Result<(), std::io::Error> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_library_files(root, &path, out)?;
            continue;
        }
        if path.extension().and_then(|ext| ext.to_str()) != Some("lib") {
            continue;
        }
        let logical = path
            .strip_prefix(root)
            .expect("library path should stay under root")
            .to_string_lossy()
            .replace('\\', "/");
        let source = fs::read_to_string(&path)?;
        out.push((logical, source));
    }
    Ok(())
}
