use std::env;
use std::fs;
use std::io::Write;
use std::path::{Path, PathBuf};

fn main() {
    println!("cargo:rerun-if-env-changed=FAUST_RS_EMBEDDED_LIB_ROOT");
    println!("cargo:rerun-if-env-changed=FAUST_RS_FAUSTLIBRARIES_ROOT");
    println!("cargo:rerun-if-env-changed=FAUST_LIB_PATH");

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR should be set"));
    let out_file = out_dir.join("embedded_faust_libraries.rs");
    let root = discover_library_root();
    let libraries = root
        .as_deref()
        .map(collect_library_sources)
        .transpose()
        .expect("embedded Faust library scan should succeed")
        .unwrap_or_default();

    let mut out = String::new();
    out.push_str("// @generated by crates/wasm-ffi/build.rs\n");
    out.push_str(&format!(
        "pub(crate) const EMBEDDED_FAUST_LIB_ROOT: Option<&str> = {};\n",
        root.as_ref()
            .map(|path| format!("Some({:?})", path.display().to_string()))
            .unwrap_or_else(|| "None".to_owned())
    ));
    out.push_str("pub(crate) const EMBEDDED_FAUST_LIBRARIES: &[(&str, &str)] = &[\n");
    for (path, source) in libraries {
        out.push_str(&format!("    ({path:?}, {source:?}),\n"));
    }
    out.push_str("];\n");

    let mut file = fs::File::create(&out_file).expect("generated source file should be writable");
    file.write_all(out.as_bytes())
        .expect("generated source file should be writable");
}

fn discover_library_root() -> Option<PathBuf> {
    for env_name in ["FAUST_RS_EMBEDDED_LIB_ROOT", "FAUST_RS_FAUSTLIBRARIES_ROOT"] {
        if let Some(path) = env::var_os(env_name).map(PathBuf::from)
            && path.is_dir()
        {
            return Some(path);
        }
    }

    if let Some(raw) = env::var_os("FAUST_LIB_PATH") {
        for candidate in env::split_paths(&raw) {
            if candidate.is_dir() {
                return Some(candidate);
            }
        }
    }

    ["/usr/local/share/faust", "/usr/share/faust"]
        .into_iter()
        .map(PathBuf::from)
        .find(|candidate| candidate.is_dir())
}

fn collect_library_sources(root: &Path) -> Result<Vec<(String, String)>, std::io::Error> {
    let mut files = Vec::new();
    collect_library_files(root, root, &mut files)?;
    files.sort_by(|(left, _), (right, _)| left.cmp(right));
    Ok(files)
}

fn collect_library_files(
    root: &Path,
    dir: &Path,
    out: &mut Vec<(String, String)>,
) -> Result<(), std::io::Error> {
    for entry in fs::read_dir(dir)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_library_files(root, &path, out)?;
            continue;
        }
        if path.extension().and_then(|ext| ext.to_str()) != Some("lib") {
            continue;
        }
        let logical = path
            .strip_prefix(root)
            .expect("library path should stay under root")
            .to_string_lossy()
            .replace('\\', "/");
        let source = fs::read_to_string(&path)?;
        out.push((logical, source));
    }
    Ok(())
}
