[package]
name = "parser"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
boxes = { path = "../boxes" }
diagnostics = { path = "../diagnostics" }
cfgrammar = "0.13.10"
lrlex = "0.13.10"
lrpar = "0.13.10"
regex-automata = "0.4"
tlib = { path = "../tlib" }

[dev-dependencies]
regex-automata = "0.4"

[build-dependencies]
cfgrammar = "0.13.10"
lrlex = "0.13.10"
lrpar = "0.13.10"
