[package]
name = "box-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[lints.rust]
unsafe_code = "allow" # Exported Box C API dereferences opaque pointers and C strings.
unused_attributes = "warn"
unused_lifetimes = "warn"

[lints.clippy]
all = "warn"

[lib]
name = "box_ffi"
crate-type = ["rlib"]

[features]
default = []
standalone-capi-globals = []

[dependencies]
boxes = { path = "../boxes" }
tlib = { path = "../tlib" }
ffi-common = { path = "../ffi-common" }
tree-ffi = { path = "../tree-ffi" }
compiler = { path = "../compiler" }
propagate = { path = "../propagate" }
codegen = { path = "../codegen" }
transform = { path = "../transform" }
fir = { path = "../fir" }
ui = { path = "../ui" }
