flowchart LR
    crate_algebra["algebra"]
    crate_box_ffi["box-ffi"]
    crate_boxes["boxes"]
    crate_codegen["codegen"]
    crate_compiler["compiler"]
    crate_cranelift_ffi["cranelift-ffi"]
    crate_diagnostics["diagnostics"]
    crate_doc["doc"]
    crate_draw["draw"]
    crate_eval["eval"]
    crate_faust_ffi["faust-ffi"]
    crate_ffi_common["ffi-common"]
    crate_fir["fir"]
    crate_foreign_call["foreign-call"]
    crate_graph["graph"]
    crate_impulse_runner["impulse-runner"]
    crate_interp_ffi["interp-ffi"]
    crate_interval["interval"]
    crate_normalize["normalize"]
    crate_parser["parser"]
    crate_propagate["propagate"]
    crate_signal_ffi["signal-ffi"]
    crate_signals["signals"]
    crate_sigtype["sigtype"]
    crate_tlib["tlib"]
    crate_transform["transform"]
    crate_tree_ffi["tree-ffi"]
    crate_ui["ui"]
    crate_wasm_ffi["wasm-ffi"]
    crate_xtask["xtask"]
